# Generated by Django 4.2.11 on 2024-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_mode',
            field=models.CharField(choices=[('T', 'TOURNAMENT'), ('O', 'OPPONENT'), ('B', 'BOT')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('B', 'BALL'), ('P', 'PADDLE'), ('G', 'BGC'), ('A', 'AVATAR')], max_length=1),
        ),
    ]
